"""empty message

Revision ID: 032a6eb485f8
Revises: a52234094da6
Create Date: 2019-05-17 11:20:29.230761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032a6eb485f8'
down_revision = 'a52234094da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Country', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=2),
               existing_server_default=sa.text('nextval(\'"Country_id_seq"\'::regclass)'))
    op.alter_column('Country', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_constraint('Visit_country_id_fkey', 'Visit', type_='foreignkey')
    op.drop_column('Visit', 'country_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Visit', sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Visit_country_id_fkey', 'Visit', 'Country', ['country_id'], ['id'])
    op.alter_column('Country', 'name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('Country', 'id',
               existing_type=sa.String(length=2),
               type_=sa.INTEGER(),
               existing_server_default=sa.text('nextval(\'"Country_id_seq"\'::regclass)'))
    # ### end Alembic commands ###
