"""empty message

Revision ID: b27222fa5069
Revises: 74c773338d30
Create Date: 2019-05-17 11:26:06.566195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27222fa5069'
down_revision = '74c773338d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Visit', sa.Column('country_id', sa.String(length=2), nullable=False))
    op.create_foreign_key(None, 'Visit', 'Country', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Visit', type_='foreignkey')
    op.drop_column('Visit', 'country_id')
    # ### end Alembic commands ###
