"""empty message

Revision ID: ec329c99517d
Revises: 526ba664c628
Create Date: 2019-05-17 10:48:33.146062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec329c99517d'
down_revision = '526ba664c628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Country', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_server_default=sa.text('nextval(\'"Country_id_seq"\'::regclass)'))
    op.alter_column('Country', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Country', 'name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('Country', 'id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_server_default=sa.text('nextval(\'"Country_id_seq"\'::regclass)'))
    # ### end Alembic commands ###
